version: '3'

tasks:
  clean:
    cmds:
      - rm -rf dist/ build/ *.egg-info eyepop.egg-info

  build:
    deps: [clean]
    cmds:
      - uv pip install build setuptools-scm
      - uv run python -m build

  install:editable:
    cmds:
      - uv pip install -e .

  test:
    cmds:
      - uv run pytest

  typecheck:
    cmds:
      - uvx mypy eyepop || true

  lint:
    desc: "Run ruff on changed files (vs main branch)"
    cmds:
      - git diff --name-only --diff-filter=AM main | grep '\.py$' | xargs -r uvx ruff check

  lint:all:
    desc: "Run ruff on all files matching ruff.toml patterns"
    cmds:
      - uvx ruff check .

  inspect-wheel:
    cmds:
      - unzip -l dist/*.whl | grep -E "py.typed|\.py$|\.pyi$"

  verify-version:
    cmds:
      - .venv/bin/python -c "import eyepop; print('Version:', eyepop.__version__)"
